[tool.bumpversion]
current_version = "2025.09.0"
parse           = '^(?P<year>\d{4})\.(?P<month>\d{2})\.(?P<patch>\d+)$'
# ← use your part names here and pad month to two digits
serialize       = ["{year}.{month:02d}.{patch}"]
tag             = true
tag_name        = "v{new_version}"
commit          = true
message         = "Release: {new_version}"

[tool.bumpversion.parts.year]
type = "calver"
# calver_format only affects how the part’s default or reset value is computed,
# you can leave this or remove if you don’t need it.

[tool.bumpversion.parts.month]
type = "calver"
# likewise, calver_format here is optional once you’re formatting via Python syntax.

[tool.bumpversion.parts.patch]
type = "integer"

[[tool.bumpversion.files]]
filename = "src/template_python_lib/__init__.py"
search   = '__version__ = "{current_version}"'
replace  = '__version__ = "{new_version}"'
